echod: move the pid file into the new directory /var/run/echod
It fixes the following error:

error: unable to remove the PID file '/var/run/echod.pid': Permission denied

because now the pid files was moved into /var/run/echod, which in turn is owned by the user, and thus
it can be removed.

"In order to delete a file, you must have write permissions on the directory that the file resides in."

https://unix.stackexchange.com/questions/49638/cannot-delete-a-file-permission-denied-why

Signed-off-by: Thiago Farina <tfransosi@gmail.com>