echod: remove '__func__' usage from M_ASSERT macro
ISO C90 does not support this predefined identifier as reported by the error below:

../src/debug.h:18:84: error: ISO C90 does not support '__func__' predefined identifier [-Werror=pedantic]
 # define M_ASSERT(expr) ((expr) ? (void) 0 : __assert_fail(#expr,__FILE__,__LINE__,__func__))
                                                                                     ^

Signed-off-by: Thiago Farina <tfransosi@gmail.com>