echod: fix build error on MacOSX
src/ulog.c:135:42: error: field precision should have type 'int', but argument has type 'unsigned long' [-Werror,-Wformat]
    len = snprintf(buf, sizeof(buf), "[%.*s] %s", strlen(timebuf), timebuf, __ulog_level_to_str(level));
                                       ~~^~       ~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
                                                             ^~~~~~~~~~~
1 error generated.

I don't think we need to set the precision, let's see.

Signed-off-by: Thiago Farina <tfarina@chromium.org>