Revert "echod: rename 'DEBUG_PRINT' macro to 'dprintf' which is shorter and function-like"
This reverts commit c2127f6f84f01255590cc3110de896838b4fab1e.

Looks like there is already a function called 'dprintf' in stdio.h, which can cause an error like this:

/usr/include/stdio.h:415:64: error: macro "dprintf" passed 3 arguments, but takes just 1
 extern int dprintf (int __fd, const char *__restrict __fmt, ...)
                                                                 ^