echod: fix another error discovered by gcc
src/ed_config.c:13:20: error: overflow in implicit constant conversion [-Werror=overflow]
   config->detach = 1;

Explanation from stackoverflow:
https://stackoverflow.com/questions/40685524/is-this-bit-field-of-size-one-actually-overflowing-when-assigning-1

This is a place in C where int and signed int/signed may differ.

unsigned int bit : 1; can hold the value 0 or 1.

Assuming 2's complement machine ...

signed int bit : 1; can hold the value 0 or -1
signed bit : 1; can hold the value 0 or -1

int bit : 1; can hold the value 0 or 1 or 0 or -1

    Each of the comma-separated multisets (int, signed, or signed int) designates the same type, except that for bitfields, it is implementation-defined whether the specifier int designates the same type as signed int or the same type as unsigned int. C11 -6.7.2 5

Using unsigned removes ambiguities.

https://stackoverflow.com/a/40685953

Signed-off-by: Thiago Farina <tfransosi@gmail.com>