echod: fix another compiler error and enable c89 build
../src/ed_cmdline.c:133:4: error: string literal of length 706 exceeds maximum
length 509 that C90 compilers are required to support [-Werror,-Woverlength-strings]
          "Options:" CRLF
	            ^~~~~~~~~~~~~~~

Signed-off-by: Thiago Farina <tfransosi@gmail.com>