tribe: use our xstrdup function in alpm_list.c
When enabling -Werror for source code under src/, it triggers
the following errors in alpm_list.c:

../src/alpm_list.c: In function ‘alpm_list_append_strdup’:
../src/alpm_list.c:146:12: error: implicit declaration of function ‘strdup’ [-Werror=implicit-function-declaration]
  if((dup = strdup(data)) && (ret = alpm_list_append(list, dup))) {
              ^
../src/alpm_list.c:146:10: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
if((dup = strdup(data)) && (ret = alpm_list_append(list, dup))) {
          ^

Changing it to use our xstrdup function, fixes these errors.

Another solution, would be to move this module into a third party
directory, and avoid compiling it with -Werror. This would require much
more complicated changes. For now, let's go with the simple fix.

Signed-off-by: Thiago Farina <tfransosi@gmail.com>