buffer: define a LIBS variable and use it
This will make git blame more effective when changing the libraries alone.

We decided to use LIBS rather than LDLIBS [1], because the former is what automake uses.

Nota that, yes, the order in which -lbuffer appears matter.

The ld(1) documentation for -l, --library says:
"The linker will search an archive only once, at the location where it is
 specified on the command line.  If the archive defines a symbol which was
 undefined in some object which appeared before the archive on the command
 line, the linker will include the appropriate file(s) from the archive.
 However, an undefined symbol in an object appearing later on the command
 line will not cause the linker to search the archive again."

In order words, what it is saying is that, if we pass -lbuffer before the object file
buffer_test.o, the linker will not search the libbuffer.a archive for the undefined symbol.

Placing -lbuffer anywhere before the buffer_test.o will cause the following:
buffer_test.c:12: undefined reference to `buffer_create'
buffer_test.c:15: undefined reference to `buffer_write'
buffer_test.c:17: undefined reference to `buffer_data'
buffer_test.c:18: undefined reference to `buffer_size'
buffer_test.c:20: undefined reference to `buffer_create'
buffer_test.c:23: undefined reference to `buffer_write'
buffer_test.c:25: undefined reference to `buffer_data'
buffer_test.c:26: undefined reference to `buffer_size'
buffer_test.c:28: undefined reference to `buffer_destroy'
buffer_test.c:29: undefined reference to `buffer_destroy'
collect2: error: ld returned 1 exit status

Hence, as pointed out in the documentation, -lbuffer has to come after the object.

Refs:
https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

Signed-off-by: Thiago Farina <tfransosi@gmail.com>